In [1]:
# Matrix addition using Python lists

A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

# Create an empty matrix
C = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

# Add corresponding elements
for i in range(len(A)):
    for j in range(len(A[0])):
        C[i][j] = A[i][j] + B[i][j]

print("Matrix A:")
for row in A:
    print(row)

print("Matrix B:")
for row in B:
    print(row)

print("Addition of Matrix A and B:")
for row in C:
    print(row)

Matrix A:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Matrix B:
[9, 8, 7]
[6, 5, 4]
[3, 2, 1]
Addition of Matrix A and B:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [2]:
# Matrix addition using NumPy

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Add the two matrices
C = A + B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of Matrix A and B:")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of Matrix A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
